[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++",
    "-C", "link-arg=/opt/homebrew/opt/llvm/lib/c++/libc++.dylib",
    "-C", "link-arg=/opt/homebrew/opt/llvm/lib/c++/libc++abi.dylib",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++",
    "-C", "link-arg=/opt/homebrew/opt/llvm/lib/c++/libc++.dylib",
    "-C", "link-arg=/opt/homebrew/opt/llvm/lib/c++/libc++abi.dylib",
]

[env]
LLVM_SYS_211_PREFIX = "/opt/homebrew/opt/llvm"
