x = [
        [
            ["1", "2"], 
            ["3", "4"],
        ],
        [   
            ["5", "6"], 
            ["7", "8"]
        ]
    ]
y = [
    [
        "2", "12"
    ],
    [
        "30", "56"
    ]
]