[package]
name = "spartan-wasm-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"

[profile.release]
opt-level = "z"
lto = true
