x = [
    { a = "0", b = ["1", "2"], c = {d = {g = "3"}, e = ["4", "5"], f = "6"} },
    { a = "7", b = ["8", "9"], c = {d = {g = "10"}, e = ["11", "12"], f = "13"} },
    { a = "14", b = ["15", "16"], c = {d = {g = "17"}, e = ["18", "19"], f = "20"} },
]